apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-sync-airflow
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/master-k8s.git'
    path: 01-infra/src/helm-charts/git-sync/
    targetRevision: main

  destination:
      namespace: orchestrator
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true
