# Imagem de exemplo, altere as bibliotecas e versão de acordo com a necessidade
FROM apache/airflow:2.9.3

# Adicionar programas específicos
# USER root

# RUN apt-get update \
#   && apt-get install -y --no-install-recommends \
#          vim \
#   && apt-get autoremove -yqq --purge \
#   && apt-get clean \
#   && rm -rf /var/lib/apt/lists/* 

# Instalar dependências do sistema para o SQL Server
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl gnupg apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Instalar dependências do Airflow
RUN pip install apache-airflow-providers-cncf-kubernetes

# Instalar providers e dependências Python
RUN pip install --no-cache-dir apache-airflow-providers-microsoft-mssql pyodbc pymssql

# Configurar o PATH para incluir o diretório caso alguma dependencia precise
# ENV PATH="/home/airflow/.local/bin:${PATH}"

# Limpar o cache do pip para manter a imagem leve
RUN pip cache purge
