apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-metastore-db
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/stack-4bi.git'
    path: Infra/src/kubernetes-yaml/database/postgresql
    targetRevision: main
    # helm:
    #   valueFiles:
    #     - postgresql-metastore.yaml
  destination:
      namespace: databases
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true

