apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-superset-db
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/stack-4bi.git'
    path: Infra/src/helm-charts/visualization/superset/postgresql
    targetRevision: main
    # helm:
    #   valueFiles:
    #     - postgresql-superset.yaml
  destination:
      namespace: databases
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true

