apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/stack-4bi.git'
    path: Infra/src/helm-charts/processing/spark-operator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
      namespace: processing
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
