apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/master-k8s.git'
    path: 01-infra/src/helm-charts/metastore/hive-metastore
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: deepstore
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true

