apiVersion: v1
kind: Secret
metadata:
  name: secret-git-sync
  namespace: orchestrator
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/IcaroMC/master-k8s.git
  username: IcaroMC
  password: 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