apiVersion: batch/v1
kind: Job
metadata:
  name: test-git-clone
  namespace: orchestrator
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p ~/.ssh && \
              echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa && \
              chmod 600 ~/.ssh/id_rsa && \
              echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts && \
              git clone git@ssh.dev.azure.com:v3/4bi-dados/master-k8s/master-k8s /tmp/repo && \
              echo "Clone OK" && ls -la /tmp/repo
          env:
            - name: GIT_SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-ssh-secret
                  key: gitSshKey
            - name: KNOWN_HOSTS
              value: |
                ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
      restartPolicy: Never
  backoffLimit: 1