apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IcaroMC/stack-4bi.git'
    path: Infra/src/helm-charts/orchestrator/airflow
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      # values: |
      #   images:
      #     airflow:
      #       repository: airflow-custom-mssql
      #       tag: latest
      #       pullPolicy: IfNotPresent          
  destination:
      namespace: orchestrator
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true
        
