apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@ssh.dev.azure.com:v3/4bi-dados/master-k8s/master-k8s'
    path: 01-infra/src/helm-charts/orchestrator/kestra
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
      namespace: orchestrator
      server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background   # Deleta em background
      - PruneLast=true # Garante que a remoção ocorra no final da sync
    automated:
      prune: true
      selfHeal: true
